/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./domain/layout/components/AppShell.vue')['default']
    DummyCard: typeof import('./domain/dummy/components/DummyCard.vue')['default']
    ExampleBadge: typeof import('./domain/common/components/ExampleBadge.vue')['default']
    Footer: typeof import('./domain/layout/components/Footer.vue')['default']
    Header: typeof import('./domain/layout/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
